### ISSUE TITLE
Issue moving to another machine

### ISSUE THREAD

**Issue by jvdoppio** [alfredapp/google-drive-workflow#31]
hey - I recently migrated my data from an older macbook pro to an m1 machine, and now whenever I try to run the workflow I get "No cache found!". I already uninstalled and reinstalled a couple of times, verified the Google Drive locations in the Volume folder, etc but no luck.. any suggestions?

**Comment by vitorgalvao** [comment]
Please don’t skip the issue template. It’s there for a reason. It’s impossible to give you an answer with the information you provided.

**Comment by jvdoppio** [comment]
apologies - where can I find it? is it just pasting the results from the diagnostics here or is there something else?

if it's just the diagnostics paste, you can find it below. otherwise let me know where to find the information and I will go get it! thanks in advance.

### Workflow version
2022.7

### Alfred version
4.6.3

### macOS version
12.2.1

### Workflow environment variables
Dict {
    ignore_list = 
    result_limit = 50
    google_drive_path = /Volumes/GoogleDrive-102995896676330937574,/Volumes/GoogleDrive-105919709885642187608
}

### Google drive paths
Exists: /Volumes/GoogleDrive-102995896676330937574
54M
30687 paths
Exists: /Volumes/GoogleDrive-105919709885642187608
19M
24773 paths

### Cache dir
tmp.db

### Cache file
Does NOT exist

### Temporary cache
16777229 2818006 -rw-r--r-- 1 jefersonvaladares staff 0 8192 "Feb 27 20:24:13 2022" "Feb 27 20:24:13 2022" "Feb 27 20:24:13 2022" "Feb 27 20:24:13 2022" 4096 16 0 /Users/jefersonvaladares/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive/tmp.db

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.launchd.googledrivecache
Installed

**Comment by vitorgalvao** [comment]
Run `:gdrebuildcache` and see if that fixes it. You’ll have to wait a while for the cache building to finish.

Also:

* Are you on Intel or M1?
* Do you know why your drives follow the pattern `/Volumes/GoogleDrive-NNNNNNNNNNNNNNNNNNNNN` instead of being children of being descendants of `/Volumes/GoogleDrive/`?
* Are both of those shared drives?

Those might be relevant to your issue, but also to another case I’m investigating.

**Comment by jvdoppio** [comment]
I have tried rebuilding the cache - I always get the "Cache rebuilt" message almost instantly, but it doesn't fix it.
I am on an M1 (previously on an intel machine that was migrated to the M1).
They follow the -pattern (not descendants).
Yes, both are google shared drives (from two different google accounts).
This exact same setup was working before - the problem started after migrating to the M1.

**Comment by vitorgalvao** [comment]
> I have tried rebuilding the cache - I always get the "Cache rebuilt" message almost instantly, but it doesn't fix it.

In that case, open the debugger when you do it. It will almost certainly show an error.

**Comment by jvdoppio** [comment]
indeed - here's the debugging output:

[14:14:32.263] Logging Started...
[14:14:36.943] Google Drive[[Keyword](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3E1DF785DD-C488-4DA0-B939-05739F26678C)] Processing complete
[14:14:36.945] Google Drive[[Keyword](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3E1DF785DD-C488-4DA0-B939-05739F26678C)] Passing output '' to [Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3E24E99691-8B40-4D5E-9803-AC2BDDEDCD32)
[14:14:37.155] ERROR: Google Drive[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3E24E99691-8B40-4D5E-9803-AC2BDDEDCD32)] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:58:in `open': Operation not permitted @ dir_initialize - /Volumes/GoogleDrive-102995896676330937574/.TemporaryItems (Errno::EPERM)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:58:in `children'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:58:in `block (2 levels) in find'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:48:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:48:in `block in find'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:43:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:43:in `find'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:565:in `find'
	from /Users/jefersonvaladares/Dropbox/backup/Alfred.alfredpreferences/workflows/user.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24/rebuild_cache:43:in `each'
	from /Users/jefersonvaladares/Dropbox/backup/Alfred.alfredpreferences/workflows/user.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24/rebuild_cache:43:in `each'
	from /Users/jefersonvaladares/Dropbox/backup/Alfred.alfredpreferences/workflows/user.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24/rebuild_cache:43:in `block in <main>'
	from /Users/jefersonvaladares/Dropbox/backup/Alfred.alfredpreferences/workflows/user.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24/rebuild_cache:42:in `each'
	from /Users/jefersonvaladares/Dropbox/backup/Alfred.alfredpreferences/workflows/user.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24/rebuild_cache:42:in `<main>'
[14:14:37.159] Google Drive[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3E24E99691-8B40-4D5E-9803-AC2BDDEDCD32)] Processing complete
[14:14:37.160] Google Drive[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3E24E99691-8B40-4D5E-9803-AC2BDDEDCD32)] Passing output '' to [Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3E0A8D830A-3042-43A3-B238-6E224D43076E)
[14:14:37.160] Google Drive[[Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3E24E99691-8B40-4D5E-9803-AC2BDDEDCD32)] Passing output '' to [Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3ED5A28DD0-88F4-4CB2-A750-118B1E0ADEE7)
[14:14:37.160] Google Drive[[Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3ED5A28DD0-88F4-4CB2-A750-118B1E0ADEE7)] Processing complete
[14:14:37.161] Google Drive[[Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3ED5A28DD0-88F4-4CB2-A750-118B1E0ADEE7)] Passing output '' to [Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3E4B6C4A31-7E4F-42E0-A702-786DE0EFDCA4)
[14:14:37.161] Google Drive[[Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3E4B6C4A31-7E4F-42E0-A702-786DE0EFDCA4)] Processing complete
[14:14:37.167] Google Drive[[Conditional](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3E4B6C4A31-7E4F-42E0-A702-786DE0EFDCA4)] Passing output '' to [Post Notification](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.1A16D292-13F2-44D1-896E-4D2E5BCB3A24%3EBD0D1F9A-0869-4EB7-AB10-AF04477C97CA)

**Comment by vitorgalvao** [comment]
I’ve seen that before and have a fix ready. It wasn’t released yet because the affected person hasn’t replied if it fixes it for them. So [you can try it instead](https://github.com/alfredapp/google-drive-workflow/files/8137071/Google.Drive.alfredworkflow.zip) and I’ll release it if it works for you.

**Comment by jvdoppio** [comment]
yes it did! works fine now.

**Comment by vitorgalvao** [comment]
Great! I’ll release that fix soon.
