### ISSUE TITLE
Unable to successfully run :gdlaunchd

### ISSUE THREAD

**Issue by jasonbraun** [alfredapp/google-drive-workflow#32]
### Diagnostic

I don't get anything copied as a result when I run !gddiagnostic - maybe because it doesn't install?

### Debugger output

```codeblock
[14:34:54.480] Google Drive[Script Filter] Queuing argument ''
[14:34:54.558] Google Drive[Script Filter] Script with argv '' finished
[14:34:54.563] Google Drive[Script Filter] {"items": [
      {
        "title": "Install Google Drive launchd service",
        "subtitle": "Periodically rebuilds the cache",
        "arg": "install"
      },
    ]}
[14:34:56.021] Google Drive[Script Filter] Processing complete
[14:34:56.022] Google Drive[Script Filter] Passing output 'install' to Run Script
[14:34:56.425] Google Drive[External] Processing complete
[14:34:56.429] Google Drive[External] Passing output '' to Delay
[14:35:07.427] Google Drive[Delay] Processing complete
[14:35:07.444] Google Drive[Delay] Passing output '' to Arg and Vars
[14:35:07.446] Google Drive[Arg and Vars] Processing complete
[14:35:07.446] Google Drive[Arg and Vars] Passing output '' to Run Script
[14:35:07.739] ERROR: Google Drive[Run Script] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:58:in `open': Operation not permitted @ dir_initialize - /Volumes/GoogleDrive/.TemporaryItems (Errno::EPERM)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:58:in `children'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:58:in `block (2 levels) in find'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:48:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:48:in `block in find'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:43:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/find.rb:43:in `find'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:565:in `find'
	from /Users/jason/Settings/Alfred.alfredpreferences/workflows/user.workflow.C9A8A2E3-EF8A-4869-8244-CA6B70749ADF/rebuild_cache:43:in `each'
	from /Users/jason/Settings/Alfred.alfredpreferences/workflows/user.workflow.C9A8A2E3-EF8A-4869-8244-CA6B70749ADF/rebuild_cache:43:in `each'
	from /Users/jason/Settings/Alfred.alfredpreferences/workflows/user.workflow.C9A8A2E3-EF8A-4869-8244-CA6B70749ADF/rebuild_cache:43:in `block in <main>'
	from /Users/jason/Settings/Alfred.alfredpreferences/workflows/user.workflow.C9A8A2E3-EF8A-4869-8244-CA6B70749ADF/rebuild_cache:42:in `each'
	from /Users/jason/Settings/Alfred.alfredpreferences/workflows/user.workflow.C9A8A2E3-EF8A-4869-8244-CA6B70749ADF/rebuild_cache:42:in `<main>'
[14:35:07.747] Google Drive[Run Script] Processing complete
[14:35:07.748] Google Drive[Run Script] Passing output '' to Run Script
[14:35:07.749] Google Drive[Run Script] Passing output '' to Conditional
[14:35:07.750] Google Drive[Conditional] Processing complete
[14:35:07.751] Google Drive[Conditional] Passing output '' to Conditional
```

**Comment by vitorgalvao** [comment]
> I don't get anything copied as a result when I run !gddiagnostic - maybe because it doesn't install?

`!gddiagnostic` doesn’t depend on anything else. You may not have waited long enough.

As to your issue, can you confirm if [this version](https://transfer.sh/lJawXm/Google%20Drive.alfredworkflow) works?

**Comment by jasonbraun** [comment]
I actually found that download on another thread on the Alfred forum right after I left this issue and it works perfectly now! Thank you so much!
